[project]
name = "infrafoundry"
package_name = "infrafoundry"
pypi_name = "infrafoundry"
description = "Infrastructure automation framework with pluggable providers (Proxmox, OPNsense, Kubernetes)"
author_name = "Eric Davis"
author_email = "6662995+endavis@users.noreply.github.com"
github_user = "endavis"
github_repo = "infrafoundry"

[template]
commit = "5486031f1f8914323ffb920ef6c979143144e6c9"
commit_date = "2026-03-02"
